name: Trigger auto deployment for compas-test-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/compas-test-app-AutoDeployTrigger-90551b41-0d17-4aba-8320-f876fe613781.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.COMPASTESTAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.COMPASTESTAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.COMPASTESTAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: compastestacr.azurecr.io
          registryUsername: ${{ secrets.COMPASTESTAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.COMPASTESTAPP_REGISTRY_PASSWORD }}
          containerAppName: compas-test-app
          resourceGroup: compas-test-rg
          imageToBuild: compastestacr.azurecr.io/compas-test-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


